### ISSUE TITLE
Ciastka nie działają na stronie otwieranej z pliku (lokalnie)

### ISSUE THREAD

**Issue by WarterPL** [AskiOfficial/ZadanieBojowe#5]
![image](https://github.com/AskiOfficial/ZadanieBojowe/assets/96202445/b551bee0-aef1-4805-b4d4-cab0d0c7561c)
Jak otwierasz z pliku, zamiast przez live server bądź githuba to nie będą działać. Myślę, że będzie to dość istotne w kontekście prezentacji jeśli by trzeba było stronę odświeżyć bo coś by się nie załadowało. 

Nie należy się na nich mocno opierać.

**Comment by AskiOfficial** [comment]
to już wina tego, że po zamknięciu lokalengo pliku cookies sie resetują

**Comment by AskiOfficial** [comment]
a przy zamykaniu strony online, zapisuja sie
